# Generated by Django 4.1.5 on 2023-01-29 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_playerp', '0002_alter_song_audio_file_alter_song_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/music/thumb_nail'),
        ),
    ]
